name: Build LabyMod Addon

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build JAR
      run: |
        mkdir -p build/libs
        jar cvf build/libs/ShowingInvisiblePlayers-LabyMod3.jar -C src/main/resources . -C src/main/java .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ShowingInvisiblePlayers-LabyMod3
        path: build/libs/*.jar
